libvfio-user: include libvfio-user as a submodule with SPDK
Also add a CONFIG_VFIO_USER config flag, it's enabled by
default.

Change-Id: I18b44c024a264516a60f743d5c366a4c7f7c6785
Signed-off-by: Changpeng Liu <changpeng.liu@intel.com>

diff --git a/configure b/configure
--- a/configure
+++ b/configure
@@ -62,6 +62,8 @@ function usage()
 	echo "                           No path required."
 	echo " virtio                    Build vhost initiator and virtio-pci bdev modules."
 	echo "                           No path required."
+	echo " muser                     Build NVMf custom muser target."
+	echo "                           No path required."
 	echo " pmdk                      Build persistent memory bdev."
 	echo "                           example: /usr/share/pmdk"
 	echo " reduce                    Build vbdev compression module."
@@ -334,6 +336,12 @@ for i in "$@"; do
 		--without-virtio)
 			CONFIG[VIRTIO]=n
 			;;
+		--with-vfio-user)
+			CONFIG[VFIO_USER]=y
+			;;
+		--without-vfio-user)
+			CONFIG[VFIO_USER]=n
+			;;
 		--with-pmdk)
 			CONFIG[PMDK]=y
 			CONFIG[PMDK_DIR]=""
@@ -448,6 +456,28 @@ else
 	BUILD_CMD=($CC -o /dev/null -x c $CPPFLAGS $CFLAGS $LDFLAGS)
 fi
 BUILD_CMD+=(-I/usr/local/include -L/usr/local/lib)
+
+if [[ "${CONFIG[VFIO_USER]}" = "y" ]]; then
+	# VFIO_USER is enabled default for x86_64 and Linux
+	if [[ $arch != x86_64* ]] || [[ $sys_name == "FreeBSD" ]]; then
+		CONFIG[VFIO_USER]="n"
+	fi
+
+	if [[ ! -d /usr/include/json-c ]] && [[ ! -d /usr/local/include/json-c ]]; then
+		echo "json-c-devel not installed, disable CONFIG_VFIO_USER"
+		CONFIG[VFIO_USER]="n"
+	fi
+
+	if [[ ! -e /usr/include/cmocka.h ]] && [[ ! -e /usr/local/include/cmocka.h ]]; then
+		echo "libcmocka-devel not installed, disable CONFIG_VFIO_USER"
+		CONFIG[VFIO_USER]="n"
+	fi
+
+	if ! hash cmake; then
+		echo "cmake not installed, disable CONFIG_VFIO_USER"
+		CONFIG[VFIO_USER]="n"
+	fi
+fi
 
 # IDXD uses Intel specific instructions.
 if [[ "${CONFIG[IDXD]}" = "y" ]]; then
